services:
  bot:
    build:
      context: .
    volumes:
      - ./bot:/bot
    environment:
      - AUDIT_CHANNEL_ID=${AUDIT_CHANNEL_ID}
      - API_TOKEN=${API_TOKEN}
      - SERVER_ID=${SERVER_ID}
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
  
  ollama:
    image: ollama/ollama:latest
    volumes: 
      - ./ollama:/root/.ollama
      - ./ollama.sh/:/ollama.sh
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    entrypoint: ['/usr/bin/bash', '/ollama.sh']